---
dist: focal
addons:
  apt:
    packages:
      - gjs
      - meson
      - npm
matrix:
  include:
    - name: Linter
      script: |
        npm install -g eslint &&
        eslint bin/* src test
    - name: Unit tests
      script: |
        meson _build &&
        ninja -C _build &&
        RUN_THOROUGH_TESTS=yes meson test -C _build
    - name: Installed test
      script: |
        meson _build &&
        ninja -C _build &&
        sudo ninja -C _build install &&
        jasmine
